# Soma de Matrizes com CUDA

Este notebook demonstra como realizar a soma de duas matrizes quadradas de tamanho 32 utilizando a biblioteca CUDA do PyTorch.

In [ ]:
%pip install -r ../requirements.txt

In [1]:
import torch

# Verificar se CUDA está disponível
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Usando dispositivo: {device}')

Usando dispositivo: cuda


## Inicialização das Matrizes

Vamos criar duas matrizes quadradas de tamanho 32 com valores aleatórios.

In [2]:
# Tamanho das matrizes
N = 32

# Criar duas matrizes aleatórias no dispositivo CUDA
#matrix_a = torch.rand((N, N), device=device)
#matrix_b = torch.rand((N, N), device=device)
matrix_a = torch.rand((N, N))
matrix_b = torch.rand((N, N))

print("Matriz A:")
print(matrix_a)

print("\nMatriz B:")
print(matrix_b)

Matriz A:
tensor([[0.3963, 0.4543, 0.5858,  ..., 0.4504, 0.3881, 0.4695],
        [0.5725, 0.3775, 0.0960,  ..., 0.0554, 0.4642, 0.1510],
        [0.9807, 0.6590, 0.1757,  ..., 0.8000, 0.2427, 0.1024],
        ...,
        [0.3592, 0.7176, 0.8184,  ..., 0.6110, 0.1880, 0.6845],
        [0.3035, 0.0574, 0.6298,  ..., 0.9055, 0.1454, 0.6360],
        [0.6614, 0.9907, 0.1469,  ..., 0.6055, 0.8927, 0.3918]])

Matriz B:
tensor([[0.9075, 0.5336, 0.7817,  ..., 0.3872, 0.3209, 0.0469],
        [0.5209, 0.3734, 0.5783,  ..., 0.1549, 0.5250, 0.4891],
        [0.5397, 0.3564, 0.4263,  ..., 0.8378, 0.2496, 0.7726],
        ...,
        [0.5405, 0.2164, 0.3317,  ..., 0.5742, 0.5903, 0.5981],
        [0.8855, 0.6558, 0.9418,  ..., 0.8125, 0.8096, 0.1924],
        [0.4015, 0.3111, 0.9784,  ..., 0.8641, 0.1121, 0.1918]])


In [4]:
matrix_a = matrix_a.to(device)
matrix_b = matrix_b.to(device)

print("Matriz A:")
print(matrix_a)

print("\nMatriz B:")
print(matrix_b)

Matriz A:
tensor([[0.3963, 0.4543, 0.5858,  ..., 0.4504, 0.3881, 0.4695],
        [0.5725, 0.3775, 0.0960,  ..., 0.0554, 0.4642, 0.1510],
        [0.9807, 0.6590, 0.1757,  ..., 0.8000, 0.2427, 0.1024],
        ...,
        [0.3592, 0.7176, 0.8184,  ..., 0.6110, 0.1880, 0.6845],
        [0.3035, 0.0574, 0.6298,  ..., 0.9055, 0.1454, 0.6360],
        [0.6614, 0.9907, 0.1469,  ..., 0.6055, 0.8927, 0.3918]],
       device='cuda:0')

Matriz B:
tensor([[0.9075, 0.5336, 0.7817,  ..., 0.3872, 0.3209, 0.0469],
        [0.5209, 0.3734, 0.5783,  ..., 0.1549, 0.5250, 0.4891],
        [0.5397, 0.3564, 0.4263,  ..., 0.8378, 0.2496, 0.7726],
        ...,
        [0.5405, 0.2164, 0.3317,  ..., 0.5742, 0.5903, 0.5981],
        [0.8855, 0.6558, 0.9418,  ..., 0.8125, 0.8096, 0.1924],
        [0.4015, 0.3111, 0.9784,  ..., 0.8641, 0.1121, 0.1918]],
       device='cuda:0')


## Soma das Matrizes

Agora, realizamos a soma das duas matrizes diretamente no dispositivo CUDA.

In [5]:
# Soma das matrizes
matrix_sum = matrix_a + matrix_b

print("\nSoma das Matrizes:")
print(matrix_sum)


Soma das Matrizes:
tensor([[1.3038, 0.9879, 1.3674,  ..., 0.8376, 0.7090, 0.5164],
        [1.0934, 0.7509, 0.6743,  ..., 0.2103, 0.9893, 0.6401],
        [1.5204, 1.0155, 0.6019,  ..., 1.6378, 0.4923, 0.8750],
        ...,
        [0.8997, 0.9341, 1.1501,  ..., 1.1852, 0.7783, 1.2826],
        [1.1890, 0.7131, 1.5716,  ..., 1.7180, 0.9550, 0.8283],
        [1.0629, 1.3017, 1.1253,  ..., 1.4696, 1.0047, 0.5836]],
       device='cuda:0')


## Transferência para a CPU

Se necessário, podemos transferir o resultado de volta para a CPU.

In [6]:
# Transferir o resultado para a CPU
matrix_sum_cpu = matrix_sum.cpu()

print("\nSoma das Matrizes (na CPU):")
print(matrix_sum_cpu)


Soma das Matrizes (na CPU):
tensor([[1.3038, 0.9879, 1.3674,  ..., 0.8376, 0.7090, 0.5164],
        [1.0934, 0.7509, 0.6743,  ..., 0.2103, 0.9893, 0.6401],
        [1.5204, 1.0155, 0.6019,  ..., 1.6378, 0.4923, 0.8750],
        ...,
        [0.8997, 0.9341, 1.1501,  ..., 1.1852, 0.7783, 1.2826],
        [1.1890, 0.7131, 1.5716,  ..., 1.7180, 0.9550, 0.8283],
        [1.0629, 1.3017, 1.1253,  ..., 1.4696, 1.0047, 0.5836]])
